name: Flutter CI/CD

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx4608m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8"

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Java
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.9'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install dependencies
        run: flutter pub get

      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=app/upload-keystore.jks" >> android/key.properties

      - name: Decode google services
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_BASE64 }}" | base64 --decode > android/app/google-services.json

      - name: Create dart defines
        run: |
          echo '${{ secrets.ENV_VARS }}' > dart_defines.json

      - name: Extract version
        run: |
            VERSION=${GITHUB_REF#refs/tags/v}
            echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0.1'
          bundler-cache: true

      - name: Build AAB
        run: |
            flutter build appbundle \
            --dart-define-from-file=dart_defines.json

      - name: Decode Play Store key
        run: |
          echo "${{ secrets.PLAY_STORE_JSON_KEY_BASE64 }}" | base64 --decode > android/key.json

      - name: Deploy to Play Store (Internal)
        working-directory: android
        run: |
          bundle install
          PLAY_STORE_JSON_KEY_PATH=key.json AAB_PATH=../build/app/outputs/bundle/release/app-release.aab bundle exec fastlane internal
